In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TASK2.csv')
df.head()

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0,0,0,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [ ]:
df.shape

(9564, 49)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 49 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   kepid              9564 non-null   int64
 1   kepoi_name         9564 non-null   object
 2   kepler_name        2359 non-null   object
 3   koi_disposition    9564 non-null   object
 4   koi_pdisposition   9564 non-null   object
 5   koi_score          8054 non-null   float64
 6   koi_fpflag_nt      9564 non-null   int64
 7   koi_fpflag_ss      9564 non-null   int64
 8   koi_fpflag_co      9564 non-null   int64
 9   koi_fpflag_ec      9564 non-null   int64
 10  koi_period         9564 non-null   float64
 11  koi_period_err1    9110 non-null   float64
 12  koi_period_err2    9110 non-null   float64
 13  koi_time0bk        9564 non-null   float64
 14  koi_time0bk_err1   9110 non-null   float64
 15  koi_time0bk_err2   9110 non-null   float64
 16  koi_impact         9201 non-null   float64
 17  koi_impact_err1    9110 non-null   float64
 18  koi_impact_err2    9110 non-null   float64
 19  koi_duration       9564 non-null   float64
 20  koi_duration_err1  9110 non-null   float64
 21  koi_duration_err2  9110 non-null   float64
 22  koi_depth          9201 non-null   float64
 23  koi_depth_err1     9110 non-null   float64
 24  koi_depth_err2     9110 non-null   float64
 25  koi_prad           9201 non-null   float64
 26  koi_prad_err1      9201 non-null   float64
 27  koi_prad_err2      9201 non-null   float64
 28  koi_teq            9201 non-null   float64
 29  koi_teq_err1       0 non-null      float64
 30  koi_teq_err2       0 non-null      float64
 31  koi_insol          9243 non-null   float64
 32  koi_insol_err1     9243 non-null   float64
 33  koi_insol_err2     9243 non-null   float64
 34  koi_model_snr      9201 non-null   float64
 35  koi_tce_plnt_num   9218 non-null   float64
 36  koi_tce_delivname  9218 non-null   object
 37  koi_steff          9201 non-null   float64
 38  koi_steff_err1     9096 non-null   float64
 39  koi_steff_err2     9081 non-null   float64
 40  koi_slogg          9201 non-null   float64
 41  koi_slogg_err1     9096 non-null   float64
 42  koi_slogg_err2     9096 non-null   float64
 43  koi_srad           9201 non-null   float64
 44  koi_srad_err1      9096 non-null   float64
 45  koi_srad_err2      9096 non-null   float64
 46  ra                 9564 non-null   float64
 47  dec                9564 non-null   float64
 48  koi_kepmag         9563 non-null   float64
dtypes: float64(39), int64(5), object(5)
memory usage: 3.6+ MB

In [ ]:
df = df.drop(['kepid', 'kepoi_name', 'kepler_name', 'koi_pdisposition', 'koi_score','koi_teq_err1', 'koi_teq_err2'], axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 42 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   koi_disposition    9564 non-null   object
 1   koi_fpflag_nt      9564 non-null   int64
 2   koi_fpflag_ss      9564 non-null   int64
 3   koi_fpflag_co      9564 non-null   int64
 4   koi_fpflag_ec      9564 non-null   int64
 5   koi_period         9564 non-null   float64
 6   koi_period_err1    9110 non-null   float64
 7   koi_period_err2    9110 non-null   float64
 8   koi_time0bk        9564 non-null   float64
 9   koi_time0bk_err1   9110 non-null   float64
 10  koi_time0bk_err2   9110 non-null   float64
 11  koi_impact         9201 non-null   float64
 12  koi_impact_err1    9110 non-null   float64
 13  koi_impact_err2    9110 non-null   float64
 14  koi_duration       9564 non-null   float64
 15  koi_duration_err1  9110 non-null   float64
 16  koi_duration_err2  9110 non-null   float64
 17  koi_depth          9201 non-null   float64
 18  koi_depth_err1     9110 non-null   float64
 19  koi_depth_err2     9110 non-null   float64
 20  koi_prad           9201 non-null   float64
 21  koi_prad_err1      9201 non-null   float64
 22  koi_prad_err2      9201 non-null   float64
 23  koi_teq            9201 non-null   float64
 24  koi_insol          9243 non-null   float64
 25  koi_insol_err1     9243 non-null   float64
 26  koi_insol_err2     9243 non-null   float64
 27  koi_model_snr      9201 non-null   float64
 28  koi_tce_plnt_num   9218 non-null   float64
 29  koi_tce_delivname  9218 non-null   object
 30  koi_steff          9201 non-null   float64
 31  koi_steff_err1     9096 non-null   float64
 32  koi_steff_err2     9081 non-null   float64
 33  koi_slogg          9201 non-null   float64
 34  koi_slogg_err1     9096 non-null   float64
 35  koi_slogg_err2     9096 non-null   float64
 36  koi_srad           9201 non-null   float64
 37  koi_srad_err1      9096 non-null   float64
 38  koi_srad_err2      9096 non-null   float64
 39  ra                 9564 non-null   float64
 40  dec                9564 non-null   float64
 41  koi_kepmag         9563 non-null   float64
dtypes: float64(36), int64(4), object(2)
memory usage: 3.1+ MB

In [ ]:
df.groupby('koi_disposition').size()

koi_disposition
CANDIDATE         2367
CONFIRMED         2357
FALSE POSITIVE    4840
dtype: int64

In [ ]:
df = df[df['koi_disposition'] != 'CANDIDATE']
df.shape

(7197, 42)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7197 entries, 0 to 9563
Data columns (total 42 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   koi_disposition    7197 non-null   object
 1   koi_fpflag_nt      7197 non-null   int64
 2   koi_fpflag_ss      7197 non-null   int64
 3   koi_fpflag_co      7197 non-null   int64
 4   koi_fpflag_ec      7197 non-null   int64
 5   koi_period         7197 non-null   float64
 6   koi_period_err1    6863 non-null   float64
 7   koi_period_err2    6863 non-null   float64
 8   koi_time0bk        7197 non-null   float64
 9   koi_time0bk_err1   6863 non-null   float64
 10  koi_time0bk_err2   6863 non-null   float64
 11  koi_impact         6939 non-null   float64
 12  koi_impact_err1    6863 non-null   float64
 13  koi_impact_err2    6863 non-null   float64
 14  koi_duration       7197 non-null   float64
 15  koi_duration_err1  6863 non-null   float64
 16  koi_duration_err2  6863 non-null   float64
 17  koi_depth          6939 non-null   float64
 18  koi_depth_err1     6863 non-null   float64
 19  koi_depth_err2     6863 non-null   float64
 20  koi_prad           6939 non-null   float64
 21  koi_prad_err1      6939 non-null   float64
 22  koi_prad_err2      6939 non-null   float64
 23  koi_teq            6939 non-null   float64
 24  koi_insol          6978 non-null   float64
 25  koi_insol_err1     6978 non-null   float64
 26  koi_insol_err2     6978 non-null   float64
 27  koi_model_snr      6939 non-null   float64
 28  koi_tce_plnt_num   6913 non-null   float64
 29  koi_tce_delivname  6913 non-null   object
 30  koi_steff          6939 non-null   float64
 31  koi_steff_err1     6840 non-null   float64
 32  koi_steff_err2     6825 non-null   float64
 33  koi_slogg          6939 non-null   float64
 34  koi_slogg_err1     6840 non-null   float64
 35  koi_slogg_err2     6840 non-null   float64
 36  koi_srad           6939 non-null   float64
 37  koi_srad_err1      6840 non-null   float64
 38  koi_srad_err2      6840 non-null   float64
 39  ra                 7197 non-null   float64
 40  dec                7197 non-null   float64
 41  koi_kepmag         7196 non-null   float64
dtypes: float64(36), int64(4), object(2)
memory usage: 2.4+ MB

In [ ]:
missing_error_attribute_names = [attr for attr in df.columns if "err" in attr]
print(missing_error_attribute_names)

['koi_period_err1', 'koi_period_err2', 'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact_err1', 'koi_impact_err2', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth_err1', 'koi_depth_err2', 'koi_prad_err1', 'koi_prad_err2', 'koi_insol_err1', 'koi_insol_err2', 'koi_steff_err1', 'koi_steff_err2', 'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad_err1', 'koi_srad_err2']

In [ ]:
df = df[['koi_disposition','koi_fpflag_nt','koi_fpflag_ss','koi_fpflag_co','koi_fpflag_ec','koi_period','koi_time0bk','koi_impact','koi_duration','koi_depth','koi_prad','koi_teq','koi_insol','koi_model_snr','koi_tce_plnt_num','koi_steff','koi_slogg','koi_srad','ra','dec','koi_kepmag']]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7197 entries, 0 to 9563
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   koi_disposition   7197 non-null   object
 1   koi_fpflag_nt     7197 non-null   int64
 2   koi_fpflag_ss     7197 non-null   int64
 3   koi_fpflag_co     7197 non-null   int64
 4   koi_fpflag_ec     7197 non-null   int64
 5   koi_period        7197 non-null   float64
 6   koi_time0bk       7197 non-null   float64
 7   koi_impact        6939 non-null   float64
 8   koi_duration      7197 non-null   float64
 9   koi_depth         6939 non-null   float64
 10  koi_prad          6939 non-null   float64
 11  koi_teq           6939 non-null   float64
 12  koi_insol         6978 non-null   float64
 13  koi_model_snr     6939 non-null   float64
 14  koi_tce_plnt_num  6913 non-null   float64
 15  koi_steff         6939 non-null   float64
 16  koi_slogg         6939 non-null   float64
 17  koi_srad          6939 non-null   float64
 18  ra                7197 non-null   float64
 19  dec               7197 non-null   float64
 20  koi_kepmag        7196 non-null   float64
dtypes: float64(16), int64(4), object(1)
memory usage: 1.2+ MB

In [ ]:
df_new1 = df.copy()

In [ ]:
df_new1['koi_disposition'] = df_new1['koi_disposition'].map({'CONFIRMED': 1, 'FALSE POSITIVE': 0})
df_new1.head()

,koi_disposition,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_time0bk,koi_impact,koi_duration,koi_depth,...,koi_teq,koi_insol,koi_model_snr,koi_tce_plnt_num,koi_steff,koi_slogg,koi_srad,ra,dec,koi_kepmag
0,1,0,0,0,0,9.488036,170.538750,0.146,2.95750,616.0,...,793.0,93.59,35.8,1.0,5455.0,4.467,0.927,291.93423,48.141651,15.347
1,1,0,0,0,0,54.418383,162.513840,0.586,4.50700,875.0,...,443.0,9.11,25.8,2.0,5455.0,4.467,0.927,291.93423,48.141651,15.347
3,0,0,1,0,0,1.736952,170.307565,1.276,2.40641,8080.0,...,1395.0,891.96,505.6,1.0,5805.0,4.564,0.791,285.53461,48.285210,15.597
4,1,0,0,0,0,2.525592,171.595550,0.701,1.65450,603.0,...,1406.0,926.16,40.9,1.0,6031.0,4.438,1.046,288.75488,48.226200,15.509
5,1,0,0,0,0,11.094321,171.201160,0.538,4.59450,1520.0,...,835.0,114.81,66.5,1.0,6046.0,4.486,0.972,296.28613,48.224670,15.714

In [ ]:
feature_columns = df_new1.columns[df_new1.columns != 'koi_disposition']
target_column = 'koi_disposition'

In [ ]:
X = df_new1[feature_columns]
y = df_new1[target_column]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10],
    'penalty': ['none', 'l2'],
}

In [ ]:
log_reg = LogisticRegression()